# Generated by Django 4.0 on 2021-12-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('mobileName', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=150)),
                ('janCode', models.IntegerField(max_length=100)),
            ],
        ),
    ]
