# Generated by Django 4.0 on 2021-12-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='janCode',
            field=models.IntegerField(),
        ),
    ]
