# Generated by Django 4.0 on 2021-12-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_jancode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='mobileName',
            new_name='modelName',
        ),
    ]
