# Generated by Django 4.0 on 2021-12-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_alter_mobile_jancode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
