# Generated by Django 4.0 on 2021-12-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Mobile'),
        ),
    ]
