# Generated by Django 4.0 on 2021-12-26 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_alter_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='janCode',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
