# Generated by Django 4.0 on 2021-12-26 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0010_alter_mobile_jancode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, default='mobile.png', null=True, upload_to='Mobile'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='janCode',
            field=models.DecimalField(decimal_places=0, max_digits=13, unique=True, validators=[django.core.validators.MinValueValidator(8, message='JAN value is between 8 and 13 digit')]),
        ),
    ]
